using System.Collections;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;
using UnityEngine.InputSystem;

public class Timer : MonoBehaviour
{
    public Text timerText;
    public Text distanceText;
    public Text lastDistanceText;
    public Text speedText;
    private float timer = 0f;
    public float clearTime = 10f; // 1ï¿½ï¿½30ï¿½b = 90ï¿½b
    public BirdControl BirdControl;
    public GameObject LongHand;
    public GameObject ShortHand;
    public GameObject TimerBack;
   
    public GameObject TitleUI;
    public GameObject PracticeUI;
    public GameObject GameUI;
   
    public GameObject ClearUI;
    public Camera mainCamera;

    private float previousZPosition = 0f; // ï¿½Oï¿½ï¿½ï¿½Zï¿½Ê’u
    private float cumulativeDistance = 0f; // ï¿½İŒvï¿½ï¿½ï¿½ï¿½
    private float elapsedTime = 0f; // ï¿½oï¿½ßï¿½ï¿½Ô‚Ìƒgï¿½ï¿½ï¿½bï¿½Lï¿½ï¿½ï¿½O
    private bool isClear = false; // ï¿½Qï¿½[ï¿½ï¿½ï¿½Nï¿½ï¿½ï¿½Aï¿½ï¿½ï¿½Ç‚ï¿½ï¿½ï¿½ï¿½ğ”»’è‚·ï¿½ï¿½tï¿½ï¿½ï¿½O
    bool isGame;
    bool isTitle;
    bool isPractice;
    Rigidbody rb;

    public float minFieldOfView = 60f; // ï¿½Åï¿½Field of View
    public float maxFieldOfView = 100f; // ï¿½Å‘ï¿½Field of View
    public float fovChangeSpeedUp = 2f; // FOVï¿½Ì•Ï‰ï¿½ï¿½ï¿½ï¿½xï¿½iï¿½ï¿½ï¿½Ô‚ï¿½ï¿½ï¿½ï¿½ï¿½Ì‘ï¿½ï¿½ï¿½ï¿½Êj
    public float fovChangeSpeedDown = 2f; // FOVï¿½Ì•Ï‰ï¿½ï¿½ï¿½ï¿½xï¿½iï¿½ï¿½ï¿½Ô‚ï¿½ï¿½ï¿½ï¿½ï¿½Ì‘ï¿½ï¿½ï¿½ï¿½Êj
    private float currentFieldOfView; // ï¿½ï¿½ï¿½İ‚ï¿½FOV

    public AutoMouseControl autoMouseControl;

    void Awake()
    {
      

        // ï¿½ï¿½Ê‚Ì•ï¿½ï¿½ï¿½1920ï¿½Aï¿½ï¿½ï¿½ï¿½ï¿½ï¿½1080ï¿½Aï¿½Eï¿½Bï¿½ï¿½ï¿½hï¿½Eï¿½ï¿½ï¿½[ï¿½hï¿½Åİ’è‚·ï¿½ï¿½
        Screen.SetResolution(640, 360, true);
        // ï¿½tï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½[ï¿½gï¿½ï¿½60ï¿½Éİ’ï¿½
        Application.targetFrameRate = 25;
        // ï¿½}ï¿½Eï¿½Xï¿½Jï¿½[ï¿½\ï¿½ï¿½ï¿½ï¿½ï¿½\ï¿½ï¿½ï¿½É‚ï¿½ï¿½Äƒï¿½ï¿½bï¿½Nï¿½ï¿½ï¿½ï¿½
        Cursor.visible = false;

     
    }
    void Start()
    {
        previousZPosition = BirdControl.transform.position.z;
        rb = BirdControl.GetComponent<Rigidbody>();

      

        // ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½FOVï¿½ï¿½İ’ï¿½
        currentFieldOfView = mainCamera.fieldOfView;
        ToTitle();
        //audioSourceWind1.PlayOneShot(soundWind1);
        audioSourceWind1.Play();
    }

    void ToTitle()
    {

        TitleUI.SetActive(true);
        PracticeUI.SetActive(false);
        GameUI.SetActive(false);
        ClearUI.SetActive(false);

        isTitle = true;
        isPractice = false;
        isGame = false;
        isClear = false;


        // ï¿½ï¿½ï¿½ï¿½ï¿½Æ‘ï¿½ï¿½xï¿½ï¿½ï¿½eï¿½Lï¿½Xï¿½gï¿½É•\ï¿½ï¿½
        lastDistanceText.text = distanceText.text;
        //= $"{currentZPosition:F0} m";
        autoMouseControl.isSinusoidalControlEnabled = true;
        


     }

    void ToPractice()
    {

        TitleUI.SetActive(false);
        PracticeUI.SetActive(true);
        GameUI.SetActive(false);
        ClearUI.SetActive(false);

        isTitle = false;
        isPractice = true;
        isGame = false;
        isClear = false;

        autoMouseControl.isSinusoidalControlEnabled = false;



    }

    void ToGame()
    {


        TitleUI.SetActive(false);
        PracticeUI.SetActive(false);
        GameUI.SetActive(true);
        ClearUI.SetActive(false);

        timer = 0;
        startPosZ = BirdControl.transform.position.z;

        isTitle = false;
        isPractice = false;
        isGame = true;
        isClear = false;

        autoMouseControl.isSinusoidalControlEnabled = false;
        


    }

    void ToClear()
    {

        TitleUI.SetActive(false);
        PracticeUI.SetActive(false);
        GameUI.SetActive(true);
        ClearUI.SetActive(true);

        isTitle = false;
        isPractice = false;
        isGame = false;
        isClear = true;

        autoMouseControl.isSinusoidalControlEnabled = true;

    }
    void KeyInput()
    {
        var keyboard = Keyboard.current;

        // Cï¿½Lï¿½[ï¿½ÅƒAï¿½vï¿½ï¿½ï¿½Pï¿½[ï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½ï¿½
        if (keyboard.cKey.wasPressedThisFrame)
        {
            QuitApplication();
        }

        // Rï¿½Lï¿½[ï¿½ÅƒVï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½Ä“Ç‚İï¿½ï¿½ï¿½
        if (keyboard.rKey.wasPressedThisFrame)
        {
            ReloadScene();
        }


        if (keyboard.tKey.wasPressedThisFrame)
        {
            ToTitle();
        }



        if (keyboard.pKey.wasPressedThisFrame)
        {
            ToPractice();
        }

       
        if (keyboard.gKey.wasPressedThisFrame)
        {
            ToGame();
        }

        

    }

    

    void Update()
    {


        KeyInput();


      
        float remainingTime=0;
        //if (!isClear&!isTitle)
        if (isGame)
            {
            timer += Time.deltaTime;
            remainingTime = clearTime - timer; // ï¿½cï¿½èï¿½Ô‚ÌŒvï¿½Z

            // ï¿½cï¿½èï¿½Ô‚ï¿½0ï¿½ï¿½ï¿½ï¿½ï¿½É‚È‚ï¿½È‚ï¿½ï¿½æ‚¤ï¿½Éï¿½ï¿½ï¿½
            remainingTime = Mathf.Max(remainingTime, 0f);

            // ï¿½ï¿½ï¿½Æ•bï¿½É•ÏŠï¿½
            float minutes = Mathf.FloorToInt(remainingTime / 60f);
            float seconds = Mathf.FloorToInt(remainingTime % 60f);

            TimerBack.GetComponent<Image>().fillAmount = remainingTime / clearTime;

            // ï¿½^ï¿½Cï¿½}ï¿½[ï¿½ï¿½ï¿½eï¿½Lï¿½Xï¿½gï¿½É•\ï¿½ï¿½ï¿½iï¿½cï¿½èï¿½Ôj
            timerText.text = string.Format("{0:00}:{1:00}", minutes, seconds);

            // ï¿½ï¿½ï¿½ï¿½ï¿½Æ‘ï¿½ï¿½xï¿½ÌŒvï¿½Zï¿½Æ•\ï¿½ï¿½
            UpdateDistanceAndSpeed();
            UpdateCameraFieldOfView();

            // ï¿½ï¿½ï¿½Ô‚ï¿½0ï¿½É‚È‚ï¿½ï¿½ï¿½ï¿½ï¿½Nï¿½ï¿½ï¿½AUIï¿½ï¿½\ï¿½ï¿½
            if (remainingTime <= 0f && !isClear)
            {
                ToClear();
              //  ClearUI.SetActive(true);
              //  isClear = true; // ï¿½Nï¿½ï¿½ï¿½Aï¿½ï¿½Ô‚É•ÏX
            }

        }
        else
            UpdateCameraFieldOfView0();


        // ï¿½ï¿½ï¿½Nï¿½ï¿½ï¿½bï¿½Nï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ê‚½ï¿½ï¿½^ï¿½Cï¿½gï¿½ï¿½ï¿½Vï¿½[ï¿½ï¿½ï¿½ÉˆÚ“ï¿½
        if (isClear && Mouse.current.leftButton.wasPressedThisFrame)
        {
            //ToTitle();
            ToTitle();
        }
    }



    // ï¿½Aï¿½vï¿½ï¿½ï¿½Pï¿½[ï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Öï¿½
    void QuitApplication()
    {
#if UNITY_EDITOR
        // Unityï¿½Gï¿½fï¿½Bï¿½^ï¿½ï¿½ï¿½Å“ï¿½ï¿½ì’†ï¿½Ìê‡ï¿½ÍƒGï¿½fï¿½Bï¿½^ï¿½ï¿½ï¿½Iï¿½ï¿½ï¿½ï¿½ï¿½È‚ï¿½
        UnityEditor.EditorApplication.isPlaying = false;
#else
            // ï¿½rï¿½ï¿½ï¿½hï¿½ï¿½ï¿½ê‚½ï¿½Aï¿½vï¿½ï¿½ï¿½Pï¿½[ï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½Å‚ÍIï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
            Application.Quit();
#endif
    }

    // ï¿½ï¿½ï¿½İ‚ÌƒVï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½Ä“Ç‚İï¿½ï¿½İ‚ï¿½ï¿½ï¿½Öï¿½
    void ReloadScene()
    {
        SceneManager.LoadScene(SceneManager.GetActiveScene().name);
    }

    // ï¿½ï¿½ï¿½ï¿½ï¿½Æ‘ï¿½ï¿½xï¿½ÌXï¿½V
    float startPosZ;
    void UpdateDistanceAndSpeed()
    {
        elapsedTime += Time.deltaTime;

        // ï¿½ï¿½ï¿½ÔŠuï¿½ï¿½ï¿½Æ‚É‹ï¿½ï¿½ï¿½ï¿½Æ‘ï¿½ï¿½xï¿½ï¿½ï¿½Xï¿½V
        if (elapsedTime >= 0.1f)
        {
            elapsedTime = 0f; // ï¿½ï¿½ï¿½Zï¿½bï¿½g

            float currentZPosition = BirdControl.transform.position.z- startPosZ;

            // ï¿½ï¿½ï¿½ï¿½ï¿½Æ‘ï¿½ï¿½xï¿½ï¿½ï¿½eï¿½Lï¿½Xï¿½gï¿½É•\ï¿½ï¿½
            distanceText.text = $"{currentZPosition:F0} m";
            speedText.text = $"{rb.velocity.z:F0} m/s";
        }
    }

public AudioSource audioSourceWind1;
public AudioSource audioSourceWind2;
public AudioClip soundWind1;
public AudioClip soundWind2;
float pans;
    // FOVï¿½ğ‘¬“xï¿½É‰ï¿½ï¿½ï¿½ï¿½ÄŠï¿½ï¿½ç‚©ï¿½É•ÏX
    void UpdateCameraFieldOfView()
    {
        float currentSpeed = rb.velocity.z;


        // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ê‡ï¿½AFOVï¿½ğ‘‰ï¿½
        if (currentSpeed >= previousZPosition)
        {
            currentFieldOfView += fovChangeSpeedUp * Time.deltaTime;
        }
        else if (currentSpeed < previousZPosition)
        {
            // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ê‡ï¿½AFOVï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
            currentFieldOfView -= fovChangeSpeedDown * Time.deltaTime;
        }

         /*
    float middleFieldOfView= (minFieldOfView+maxFieldOfView)/2;
    if( currentFieldOfView< middleFieldOfView ){
         SEVolume(audioSourceWind1,soundWind1,true);
         SEVolume(audioSourceWind2,soundWind2,false);
 
    
    }
    else{
         SEVolume(audioSourceWind1,soundWind1,false);
         SEVolume(audioSourceWind2,soundWind2,true);
       
    }*/


        // FOVï¿½Ì”ÍˆÍ‚ğ§Œï¿½
        currentFieldOfView = Mathf.Clamp(currentFieldOfView, minFieldOfView, maxFieldOfView);
 float FieldOfViewMul= currentFieldOfView/minFieldOfView;
     audioSourceWind1.pitch = FieldOfViewMul*FieldOfViewMul*FieldOfViewMul+1f;
     audioSourceWind1.volume= FieldOfViewMul*FieldOfViewMul-0.9f;
     float panSpeed = 10f*FieldOfViewMul*FieldOfViewMul;
    // pans+=panSpeed;
      float panValue = Mathf.Sin(Time.time*panSpeed); // panSpeed ã¯å‹•ãã®é€Ÿã•
      //audioSourceWind1.panStereo = panValue;
        // ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½ï¿½FOVï¿½É“Kï¿½p
        mainCamera.fieldOfView = currentFieldOfView;

        // ï¿½Oï¿½ï¿½Ì‘ï¿½ï¿½xï¿½ï¿½ï¿½Xï¿½V
        previousZPosition = currentSpeed;
    }
void SEVolume(AudioSource audioSource,AudioClip sound, bool up)
{
    if (!up)
    {
        // éŸ³é‡ã‚’ä¸‹ã’ã‚‹å‡¦ç†
        if (audioSource.volume > 0)
        {
            audioSource.volume -= Time.deltaTime * 1f; // å¾ã€…ã«éŸ³é‡ã‚’æ¸›ã‚‰ã™

            if (audioSource.volume < 0.1f)
            {
                audioSource.volume = 0; // ãƒã‚¤ãƒŠã‚¹ã«ã¯ãªã‚‰ãªã„ã‚ˆã†ã«ã™ã‚‹
                audioSource.Stop(); // å®Œå…¨ã«éŸ³é‡ãŒä¸‹ãŒã£ãŸã‚‰åœæ­¢
            }
        }
    }
    else
    {
        // éŸ³é‡ã‚’ä¸Šã’ã‚‹å‡¦ç†
        if (!audioSource.isPlaying)
        {
            audioSource.Play(); // å†ç”ŸãŒåœæ­¢ã—ã¦ã„ã‚‹å ´åˆã®ã¿å†ç”Ÿé–‹å§‹
            audioSource.PlayOneShot(sound);
            audioSource.volume = 1f; // éŸ³é‡ã®ä¸Šé™ã‚’ 1 ã«åˆ¶é™
          
        }

        audioSource.volume += Time.deltaTime * 1f; // å¾ã€…ã«éŸ³é‡ã‚’ä¸Šã’ã‚‹

        if (audioSource.volume > 1f)
        {
            audioSource.volume = 1f; // éŸ³é‡ã®ä¸Šé™ã‚’ 1 ã«åˆ¶é™
        }
    }
}

    void UpdateCameraFieldOfView0()
    {
       if (100 < currentFieldOfView)
        {
            // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ê‡ï¿½AFOVï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
            currentFieldOfView -= fovChangeSpeedDown * Time.deltaTime;
            mainCamera.fieldOfView = currentFieldOfView;
        }

        // FOVï¿½Ì”ÍˆÍ‚ğ§Œï¿½
       // currentFieldOfView = Mathf.Clamp(currentFieldOfView, minFieldOfView, maxFieldOfView);

        // ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½ï¿½FOVï¿½É“Kï¿½p
       

        // ï¿½Oï¿½ï¿½Ì‘ï¿½ï¿½xï¿½ï¿½ï¿½Xï¿½V
        //previousZPosition = currentSpeed;
    }


}
