using UnityEngine;
using System.Collections;

public class WaterSplashRaycast : MonoBehaviour
{
    public GameObject waterSplashEffectPrefab; // ï¿½ï¿½ï¿½Ìƒpï¿½[ï¿½eï¿½Bï¿½Nï¿½ï¿½ï¿½Vï¿½Xï¿½eï¿½ï¿½ï¿½Ìƒvï¿½ï¿½ï¿½nï¿½u
    public GameObject mapParticlePrefab; // Mapï¿½Ìƒpï¿½[ï¿½eï¿½Bï¿½Nï¿½ï¿½ï¿½Vï¿½Xï¿½eï¿½ï¿½ï¿½Ìƒvï¿½ï¿½ï¿½nï¿½u
    public GameObject mapParticleGroundPrefab; // Mapï¿½Ìƒpï¿½[ï¿½eï¿½Bï¿½Nï¿½ï¿½ï¿½Vï¿½Xï¿½eï¿½ï¿½ï¿½Ìƒvï¿½ï¿½ï¿½nï¿½u
    public Transform birdTransform; // ï¿½ï¿½ï¿½ï¿½Transform
    public LayerMask waterLayerMask; // ï¿½ï¿½ï¿½Ìƒï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½}ï¿½Xï¿½N
    public LayerMask mapLayerMask; // Mapï¿½Ìƒï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½}ï¿½Xï¿½N
    public float raycastDistance = 10.0f; // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Raycastï¿½Ì‹ï¿½ï¿½ï¿½
    public float splashInterval = 0.2f; // ï¿½pï¿½[ï¿½eï¿½Bï¿½Nï¿½ï¿½ï¿½ğ¶ï¿½ï¿½ï¿½ï¿½ï¿½ÔŠu
    public GameObject FocusParticleObject;
    ParticleSystem FocusParticle;
    Rigidbody rb;
    void Start()
    {
        rb = GetComponent<Rigidbody>();
        FocusParticle = FocusParticleObject.GetComponent<ParticleSystem>();

    }
    void FixedUpdate()
    {

        if (FocusParticle.isPlaying)
        {
            // ãƒ‘ãƒ¼ãƒ†ã‚£ã‚¯ãƒ«ãŒå†ç”Ÿä¸­ãªã‚‰åœæ­¢
            FocusParticle.Stop();
        }

        //if (FocusParticleObject.activeSelf == true)
        //   FocusParticleObject.SetActive(false);
        if (Player.transform.position.y < ground)
        {

            if (rb.velocity.z > 0)
                rb.AddForce(rb.transform.forward * speedDownMultiplier);

        }

        // ï¿½ï¿½ï¿½ÌˆÊ’uï¿½ï¿½ï¿½ç‰ºï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Rayï¿½ğ“Š‚ï¿½ï¿½ï¿½
        Ray ray = new Ray(birdTransform.position + Vector3.up * 0f, Vector3.down);
        RaycastHit hit;
      
        // ï¿½ï¿½ï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½ï¿½Rayï¿½ï¿½ï¿½qï¿½bï¿½gï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½`ï¿½Fï¿½bï¿½N
        if (Physics.Raycast(ray, out hit, raycastDistance, waterLayerMask))
        {

        
            // ï¿½qï¿½bï¿½gï¿½ï¿½ï¿½ï¿½ï¿½Ê’uï¿½Éï¿½ï¿½Ìƒpï¿½[ï¿½eï¿½Bï¿½Nï¿½ï¿½ï¿½ğ¶ï¿½
            SpawnWaterSplash(hit.point);
            speedUp();
        }
        // Mapï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½ï¿½Rayï¿½ï¿½ï¿½qï¿½bï¿½gï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½`ï¿½Fï¿½bï¿½N
        else if (Physics.Raycast(ray, out hit, raycastDistance, mapLayerMask))
        {
            // ï¿½qï¿½bï¿½gï¿½ï¿½ï¿½ï¿½ï¿½Ê’uï¿½ï¿½Mapï¿½Ìƒpï¿½[ï¿½eï¿½Bï¿½Nï¿½ï¿½ï¿½ğ¶ï¿½
            if (hit.point.y > ground)
            {
                SpawnMapParticle(hit.point);
                speedUp();
            }
            else
            {
                SpawnMapGroundParticle(hit.point);
            }
        }
    }

    // ï¿½ï¿½ï¿½ï¿½ï¿½Ô‚ï¿½ï¿½Ìƒpï¿½[ï¿½eï¿½Bï¿½Nï¿½ï¿½ï¿½ğ¶ï¿½
    void SpawnWaterSplash(Vector3 hitPosition)
    {
        for (int i = 0; i < 3; i++)
        {
            Vector3 randomOffset = new Vector3(Random.Range(-1.0f, 1.0f), 0, Random.Range(-1.0f, 1.0f));
            Vector3 spawnPosition = hitPosition + randomOffset;

            // Xï¿½ï¿½ï¿½ï¿½-90ï¿½xï¿½ï¿½]ï¿½ï¿½ï¿½Äƒpï¿½[ï¿½eï¿½Bï¿½Nï¿½ï¿½ï¿½ï¿½ï¿½qï¿½bï¿½gï¿½Ê’uï¿½Éï¿½ï¿½ï¿½
            GameObject splash = Instantiate(waterSplashEffectPrefab, spawnPosition, Quaternion.Euler(-90, 0, 0));

            // ï¿½pï¿½[ï¿½eï¿½Bï¿½Nï¿½ï¿½ï¿½ï¿½0.2ï¿½bï¿½ï¿½Éíœ
            Destroy(splash, 0.5f); // ï¿½pï¿½[ï¿½eï¿½Bï¿½Nï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½ï¿½ğ’²ï¿½
        }
    }

    public float ground = 0f;
    // Mapï¿½pï¿½Ìƒpï¿½[ï¿½eï¿½Bï¿½Nï¿½ï¿½ï¿½ğ¶ï¿½
    void SpawnMapParticle(Vector3 hitPosition)
    {
       
          for (int i = 0; i < 3; i++)
            {
                Vector3 randomOffset = new Vector3(Random.Range(-1.0f, 1.0f), 0, Random.Range(-1.0f, 1.0f));
                Vector3 spawnPosition = hitPosition + randomOffset;

            
              
                    // Xï¿½ï¿½ï¿½ï¿½-90ï¿½xï¿½ï¿½]ï¿½ï¿½ï¿½Äƒpï¿½[ï¿½eï¿½Bï¿½Nï¿½ï¿½ï¿½ï¿½ï¿½qï¿½bï¿½gï¿½Ê’uï¿½Éï¿½ï¿½ï¿½
                      GameObject mapParticle = Instantiate(mapParticlePrefab, spawnPosition, Quaternion.Euler(-90, 0, 0));
              
                // ï¿½pï¿½[ï¿½eï¿½Bï¿½Nï¿½ï¿½ï¿½ï¿½0.5ï¿½bï¿½ï¿½Éíœ
                Destroy(mapParticle, 0.5f);
            }

       
    }

    void SpawnMapGroundParticle(Vector3 hitPosition)
    {

        for (int i = 0; i < 3; i++)
        {
            Vector3 randomOffset = new Vector3(Random.Range(-1.0f, 1.0f), 0, Random.Range(-1.0f, 1.0f));
            Vector3 spawnPosition = hitPosition + randomOffset;




            GameObject mapParticle = Instantiate(mapParticleGroundPrefab, spawnPosition, Quaternion.Euler(-90, 0, 0));

            // ï¿½pï¿½[ï¿½eï¿½Bï¿½Nï¿½ï¿½ï¿½ï¿½0.5ï¿½bï¿½ï¿½Éíœ
            Destroy(mapParticle, 0.5f);
        }


    }
    public GameObject Player;
    public float forceMultiplierForward;
    public float speedDownMultiplier;

    public void speedUp()
    {
     rb.AddForce(rb.transform.forward * forceMultiplierForward);

       // if (!FocusParticle.isPlaying)
      //  {
       //     // ãƒ‘ãƒ¼ãƒ†ã‚£ã‚¯ãƒ«ãŒå†ç”Ÿä¸­ãªã‚‰åœæ­¢
            FocusParticle.Play();
        //}
        // if (FocusParticleObject.activeSelf == false)
        //{
        // FocusParticleObject.SetActive(true);

       // FocusParticle.Stop();  // ï¿½ï¿½xï¿½ï¿½~ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½Äï¿½
          //  FocusParticle.Play();
       // }
    }
    public void speedDown()
    {
       
       
    }
}
